"""Scene list and talking points, one per beat (pause point), in order.

make_presenter.py turns this into PRESENTER_GUIDE.md and the notes panel of
player.html. If a scene gains or loses a beat, its list here must follow.
"""

SCENES = [
    # (file, class, title, part of the talk)
    ("s00_big_picture.py", "BigPicture", "The big picture", "What it is"),
    ("s01_complex_euler.py", "ComplexToEuler", "Complex numbers and Euler's formula", "Background"),
    ("s02_exponentials.py", "ComplexExponentials", "The complex exponential e^{st}", "Background"),
    ("s03_integrals.py", "IntegralsConverge", "Integrals and convergence", "Background"),
    ("s04_fourier.py", "FourierRecap", "Fourier recap, and where it fails", "Background"),
    ("s05_lti.py", "HowItComesUp", "How it comes up: LTI systems", "How it comes up"),
    ("s06_definition.py", "LaplaceDefinition", "What it is: the definition", "What it is"),
    ("s07_landscape.py", "SPlaneLandscape", "Picturing X(s): the s-plane landscape", "What it is"),
    ("s08_uses.py", "HowItsUsed", "How it is used", "How it is used"),
    ("s09_examples_sided.py", "RightVsLeftSided", "Examples 9.1 and 9.2: same X(s), different ROC", "Examples"),
    ("s10_examples_landscapes.py", "LandscapeExamples", "Examples 9.3, 9.4, 9.5", "Examples"),
    ("s11_roc_properties.py", "ROCProperties", "ROC properties 1 to 5", "The ROC"),
    ("s12_roc_examples.py", "ROCStrips", "ROC properties 6 to 8, Examples 9.7 and 9.8", "The ROC"),
    ("s13_inverse.py", "InverseLaplace", "The inverse Laplace transform", "Inverse transform"),
    ("s14_partial_fractions.py", "PartialFractions", "Partial fractions, Examples 9.9 to 9.11", "Inverse transform"),
]

NOTES = {
    "BigPicture": [
        "This is a damped oscillation, x(t) = e^(-0.5t) cos 2t for t ≥ 0. Today's question: what does the Laplace transform turn it into?",
        "It becomes a function X(s) on the complex s-plane. We draw its size |X(s)| as a height, so we get a landscape. The bright part of the floor is the region of convergence (ROC); outside it the surface is ghosted.",
        "The two spikes are poles at s = -0.5 ± 2j. Their real part (-0.5) is the decay rate of x(t); their imaginary part (±2) is its frequency. Where the spikes stand tells you how the signal behaves.",
        "The yellow curve is the landscape along the jω-axis (σ = 0). That slice is |X(jω)|, the Fourier transform. Laplace keeps the whole plane; Fourier is one line of it.",
        "The formula we will build up to: X(s) = integral of x(t) e^(-st) dt. Every piece of it gets its own picture.",
        "Plan: background (complex numbers, e^(st), integrals, Fourier), where Laplace comes from (LTI systems), what it is, how it is used, the ROC, and the inverse transform.",
    ],
    "ComplexToEuler": [
        "A complex number is a point, or an arrow from the origin, in a plane: horizontal = real part, vertical = imaginary part.",
        "z = a + jb: go a along the real axis and b along the imaginary axis. Engineers write j for the square root of -1.",
        "Multiplying by j turns the arrow 90 degrees anticlockwise without changing its length.",
        "Do it twice: 180 degrees, the arrow points the opposite way. So j times j = -1. That is what j means geometrically.",
        "Any arrow is also described by its length r = |z| and its angle θ: z = r(cos θ + j sin θ).",
        "Multiplying by w scales by |w| and rotates by the angle of w: lengths multiply, angles add. Remember this: e^(-sτ) and H(s) later act on spirals exactly like this.",
        "e^(jθ) is the point on the unit circle at angle θ. Its horizontal shadow is cos θ and its vertical shadow is sin θ: e^(jθ) = cos θ + j sin θ.",
        "So every complex number is z = r e^(jθ): a length times a pure rotation.",
        "Now let the angle grow with time, θ = ωt. e^(jωt) is an arrow spinning at ω radians per second.",
        "Give time its own axis. The tip traces a helix: rotation in the complex plane plus steady motion along t.",
        "Look at the helix's shadows: on the floor (real part) we get cos ωt, on the back wall (imaginary part) sin ωt. Sinusoids are shadows of one spinning arrow.",
        "ω sets how fast it spins: bigger ω means tighter coils. A negative ω spins the other way.",
        "e^(jωt) and e^(-jωt): same speed, opposite twist.",
        "Add them and halve: the yellow arrow always lies on the real axis, so the sum stays in the real plane.",
        "From the side, the imaginary parts are sin and -sin, and they cancel exactly.",
        "From above, the real parts agree: cos ωt = (e^(jωt) + e^(-jωt)) / 2. Real signals are pairs of opposite spirals, which is why the poles of real signals come in conjugate pairs.",
    ],
    "ComplexExponentials": [
        "First the real exponential e^(σt). With σ < 0 it decays towards 0.",
        "With σ = 0 it stays at 1.",
        "With σ > 0 it grows without bound.",
        "Now make s = σ + jω complex. e^(st) = e^(σt) e^(jωt): the e^(jωt) part spins, the e^(σt) part sets the size. Together they make a spiral.",
        "The red funnel is the envelope e^(σt); the spiral always lies on it.",
        "The small plane at the bottom left is the s-plane. Every point s picks out one spiral e^(st).",
        "Left of the jω-axis (σ < 0) the funnel narrows and the spiral dies out.",
        "On the jω-axis (σ = 0) it is a pure helix that never decays or grows. These are Fourier's building blocks, e^(jωt).",
        "Right of the axis (σ > 0) the funnel widens and the spiral blows up.",
        "Moving up or down changes ω: faster spin, slower spin, or below the axis the spin reverses.",
        "On the real axis (ω = 0) there is no spin at all, just e^(σt).",
        "So the s-plane is a map of every exponential behaviour: left half decays, right half grows, the jω-axis oscillates forever.",
        "A point s and its mirror image s* give opposite spirals; their average is the real signal e^(σt) cos ωt, a damped cosine.",
        "Seen from above: the damped cosine. Real oscillating signals always come from such conjugate pairs.",
    ],
    "IntegralsConverge": [
        "An integral adds up area. The area under e^(-t) from 0 to T grows with T but levels off at 1: the improper integral to ∞ converges.",
        "If the integrand grows, like e^(0.12t), the area keeps growing forever: the integral diverges. The Laplace transform is an integral to ∞, so convergence is the whole story.",
        "Now a complex integrand: e^(-st) with s = 0.35 + 1.5j is a shrinking spiral (left). Integrating it means adding up tiny arrows.",
        "Right panel: the running total, the integral from 0 to T of e^(-st), drawn in the complex plane. Its velocity at each instant is the integrand (blue arrow). The spiral shrinks, so the steps shrink, and the path spirals into one point: 1/s.",
        "Change ω: the limit point 1/s moves, but the path still settles.",
        "At σ = 0 the integrand never shrinks: the running total goes round a circle forever and never settles.",
        "With σ < 0 the steps grow and the path spirals outwards: the integral diverges. So the integral of e^(-st) from 0 to ∞ equals 1/s only when Re{s} > 0.",
        "Why only σ matters: |e^(-st)| = e^(-σt). The jω part only rotates; the size, and so convergence, is decided by σ.",
    ],
    "FourierRecap": [
        "Recall Fourier: a signal, here a rectangular pulse, can be built out of sinusoids.",
        "Each lane holds one cosine at frequency ω with the right amplitude. Slide them forward and add: the yellow partial sum approaches the pulse.",
        "With just 13 frequencies we already have the pulse, with ripples at the edges.",
        "The heights of the waves, plotted against ω on the side wall, form the spectrum X(jω): how much of each frequency the signal contains.",
        "Synthesis: x(t) = 1/(2π) times the integral of X(jω) e^(jωt) dω adds all the spinning arrows back together.",
        "The same waterfall from another angle; for this pulse the spectrum is 2 sin(ω)/ω.",
        "The problem: x(t) = e^(0.25t) u(t) grows. The Fourier integrand x(t) e^(-jωt) is a growing spiral and the integral diverges: no Fourier transform. The same happens for unstable systems.",
        "Idea: first multiply by a decaying weight e^(-σt).",
        "At σ = 0.25 the weight exactly cancels the growth: the spiral neither grows nor shrinks, which is still not enough to converge.",
        "For σ > 0.25 the weighted integrand shrinks and the integral converges.",
        "The Fourier transform of the weighted signal x(t) e^(-σt) is exactly what we will call the Laplace transform X(σ + jω).",
    ],
    "HowItComesUp": [
        "An LTI system is completely described by its impulse response h(t). The output is the convolution y(t) = integral of h(τ) x(t − τ) dτ.",
        "Read h(τ) (red, on the side wall) as weights: how much the input from τ seconds ago still matters now.",
        "Each lane is the input delayed by τ and scaled by h(τ).",
        "Adding all the lanes gives the output y(t) in yellow. Convolution is a weighted sum of delayed copies of the input.",
        "Now feed in a complex exponential e^(st), a spiral.",
        "Delay it by τ: the purple spiral e^(s(t − τ)).",
        "The delayed spiral is exactly the original turned by ωτ and scaled by e^(-στ): e^(s(t − τ)) = e^(-sτ) e^(st). A delay is just multiplication by a complex number.",
        "So every delayed copy is a multiple of e^(st), and so is their weighted sum: y(t) = H(s) e^(st). The same spiral comes out, only rotated and scaled.",
        "H(s) = integral of h(τ) e^(-sτ) dτ is one complex number for each s. e^(st) is an eigenfunction of every LTI system and H(s) is its eigenvalue.",
        "On s = jω, H(jω) is the frequency response, the Fourier transform of h. For a general s it is the Laplace transform of h. That is how the Laplace transform comes up.",
    ],
    "LaplaceDefinition": [
        "Definition: X(s) = integral from -∞ to ∞ of x(t) e^(-st) dt, with s = σ + jω. We write x(t) ↔ X(s).",
        "Split e^(-st) = e^(-σt) e^(-jωt): X(σ + jω) is the Fourier transform of x(t) e^(-σt). For each σ, it is an ordinary Fourier transform of a weighted signal.",
        "Take x(t) = e^(0.5t) u(t). It grows, so it has no Fourier transform.",
        "Each lane is x(t) e^(-σt) for one value of σ (the depth axis). Red lanes still grow, green lanes decay, and the grey one at σ = 0.5 is flat.",
        "Sweep σ with the yellow slice: once σ > 0.5 the weight beats the growth and the weighted signal decays.",
        "Those values of σ form the region of convergence: σ > 0.5.",
        "On the s-plane ω makes no difference to convergence, so the ROC is the half-plane Re{s} > 0.5. Here X(s) = 1/(s - 0.5).",
        "The jω-axis (where Fourier lives) is outside the ROC, so there is no Fourier transform, but the Laplace transform exists. That is Laplace's first advantage.",
    ],
    "SPlaneLandscape": [
        "Example 9.1: x(t) = e^(-t) u(t), X(s) = 1/(s + 1). At each point s, X(s) is one complex number; for example X(0.5 + j) = 0.46 - 0.31j.",
        "Plot its size |X(s)| as a height above that point.",
        "Do that for every s and you get a landscape over the s-plane.",
        "At s = -1 the denominator is zero and X blows up: a pole, drawn as a chimney that goes up forever (we cut it off).",
        "The ROC Re{s} > -1 is where the integral converges, so only that part is the Laplace transform. The formula 1/(s + 1) continues past it (ghosted), but the integral does not.",
        "Slice along the jω-axis: |X(jω)| = 1/√(1 + ω²), the Fourier magnitude, projected on the back wall. The jω-axis is inside the ROC, so the Fourier transform exists.",
        "Example 9.3: X(s) = (s - 1)/((s + 1)(s + 2)). Zeros (numerator = 0, drawn o) are where the landscape touches the floor; poles (denominator = 0, drawn x) shoot up.",
        "Seen from above, the landscape becomes the pole-zero plot: the pole-zero plot is a map of this landscape.",
    ],
    "HowItsUsed": [
        "The velocity of e^(st) is s times its position: d/dt e^(st) = s e^(st). The yellow arrow (velocity) is the blue arrow (position) turned by the angle of s and stretched by |s|.",
        "So differentiation becomes multiplication by s: dx/dt ↔ s X(s) (bilateral transform, Lecture 7).",
        "Take a second-order system, y'' + 2y' + 5y = x(t), the same shape as a mass-spring-damper.",
        "Transform both sides: every d/dt becomes a factor s, so s² Y + 2s Y + 5 Y = X. The differential equation is now algebra.",
        "H(s) = Y/X = 1/(s² + 2s + 5), with poles at s = -1 ± 2j.",
        "Each pole p seeds a mode e^(pt), drawn as a spiral rising from the pole along a time axis. Left-half-plane poles give shrinking spirals.",
        "The two conjugate modes add up to the real impulse response h(t) = (1/2) e^(-t) sin 2t: a decaying oscillation.",
        "Move the poles closer to the jω-axis: slower decay, the system rings longer (less damping).",
        "On the jω-axis the oscillation never dies: marginally stable.",
        "In the right half-plane the response grows without bound: unstable. A causal system is stable when all its poles are in the left half-plane.",
        "Now h(t) grows, so it has no Fourier transform, but the Laplace transform still exists with ROC Re{s} > 0.22. Laplace can analyse unstable systems.",
        "Summary: convolution becomes multiplication, differential equations become algebra, pole positions tell you stability, feedback loops become simple algebra, and all of it works for growing signals.",
    ],
    "RightVsLeftSided": [
        "Example 9.1: x(t) = e^(-t) u(t). The integrand x(t) e^(-st) = e^(-(s+1)t) lives on t > 0. The test point s is in the inset.",
        "The integrand's envelope is e^(-(σ+1)t), which shrinks only if σ > -1. Move s across σ = -1 and the spiral grows: the integral diverges.",
        "So X(s) = 1/(s + 1) with ROC Re{s} > -1, to the right of the pole.",
        "Example 9.2: x(t) = -e^(-t) u(-t), which is non-zero only for t < 0. The integrand now lives on the negative time axis.",
        "Now it must shrink as t goes to -∞, which needs σ + 1 < 0. Crossing σ = -1 to the right makes it diverge.",
        "The result is X(s) = 1/(s + 1) again, but with ROC Re{s} < -1, to the left of the pole.",
        "Same algebraic X(s), different ROC, different signal. An X(s) without its ROC is an incomplete answer.",
    ],
    "LandscapeExamples": [
        "Example 9.3: x(t) = 3e^(-2t) u(t) - 2e^(-t) u(t). Each term has its own ROC: Re{s} > -2 and Re{s} > -1.",
        "The sum converges only where both terms converge: the intersection Re{s} > -1. X(s) = (s - 1)/((s + 1)(s + 2)).",
        "The landscape with the ROC lit.",
        "Example 9.4: e^(-2t) u(t) + e^(-t) cos(3t) u(t). By Euler, cos 3t gives two exponentials, so the poles are -2 and -1 ± 3j (a conjugate pair, as for any real signal). The zeros are at about -1.25 ± 2.11j.",
        "The ROC Re{s} > -1 contains the jω-axis, so the Fourier transform exists. The slice along jω peaks near ω = ±3 because it passes close to the poles at -1 ± 3j: that is resonance.",
        "Example 9.5: δ(t) - (4/3) e^(-t) u(t) + (1/3) e^(2t) u(t). The transform of δ(t) is 1 for every s. X(s) = (s - 1)²/((s + 1)(s - 2)): poles at -1 and 2, a double zero at 1.",
        "ROC = intersection = Re{s} > 2. The jω-axis is outside it: no Fourier transform, because the e^(2t) term grows.",
        "Far from the poles |X(s)| tends to 1: that constant is the δ(t) term.",
    ],
    "ROCProperties": [
        "Property 1: |x(t) e^(-(σ + jω)t)| = |x(t)| e^(-σt). Two test points with the same σ but different ω give different spirals with exactly the same envelope.",
        "So if one point on a vertical line converges, every point on that line does.",
        "The ROC is made of whole vertical lines: a vertical strip, a half-plane, or the whole plane.",
        "Property 2: at a pole X(s) is infinite, so the integral cannot converge there. Poles sit on ROC boundaries, never inside.",
        "Property 3, Example 9.6: x(t) = e^(-t) on 0 < t < 2, X(s) = (1 - e^(-2(s+1)))/(s + 1). It looks like a pole at s = -1, but there 0/0 gives 2 (L'Hôpital): the landscape has height 2, no spike.",
        "A finite-duration, absolutely integrable signal gives a finite integral for every s: the ROC is the entire s-plane. Instead of a pole there are zeros at s = -1 ± jπk. Big on the left, but never infinite.",
        "Properties 4 and 5 use the weight e^(-σt), drawn as a surface over (t, σ).",
        "Right-sided signal: only t > 0 matters. There, increasing σ only lowers the weight (green slice under grey). If σ₀ converges, every σ > σ₀ converges: the ROC extends to the right.",
        "Left-sided signal: only t < 0 matters, and there decreasing σ lowers the weight. The ROC extends to the left.",
    ],
    "ROCStrips": [
        "Example 9.7: x(t) = e^(-b|t|) is two-sided. Split it into a right part e^(-bt) u(t) (blue) and a left part e^(bt) u(-t) (red).",
        "Right part: ROC Re{s} > -b. Left part: ROC Re{s} < b. Both must converge, which leaves the strip -b < Re{s} < b (Property 6).",
        "X(s) = -2b/(s² - b²), with poles at ±b on the edges of the strip.",
        "Make b smaller: the signal decays more slowly and the strip gets thinner.",
        "For b ≤ 0 the two half-planes no longer overlap: no ROC, so no Laplace transform at all.",
        "Properties 7 and 8 (rational X(s)): ROC edges pass through poles, so the poles chop the plane into vertical strips.",
        "Right-sided: right of the rightmost pole. Left-sided: left of the leftmost pole. Two-sided: a strip between two poles.",
        "Example 9.8: X(s) = 1/((s + 1)(s + 2)), poles at -1 and -2, so there are three possible ROCs.",
        "Re{s} > -1 gives the right-sided signal x(t) = (e^(-t) - e^(-2t)) u(t).",
        "Re{s} < -2 gives the left-sided signal x(t) = (-e^(-t) + e^(-2t)) u(-t).",
        "-2 < Re{s} < -1 gives the two-sided signal x(t) = -e^(-t) u(-t) - e^(-2t) u(t).",
        "One X(s), three signals: the ROC picks the signal. How do we compute them? That is the inverse transform.",
    ],
    "InverseLaplace": [
        "Start from X(σ + jω) = Fourier transform of x(t) e^(-σt).",
        "Undo the Fourier transform: x(t) e^(-σt) = 1/(2π) times the integral of X(σ + jω) e^(jωt) dω.",
        "Multiply both sides by e^(σt): x(t) = 1/(2π) times the integral of X(σ + jω) e^((σ + jω)t) dω.",
        "Substitute s = σ + jω (σ fixed, ds = j dω): x(t) = 1/(2πj) times the integral of X(s) e^(st) ds from σ - j∞ to σ + j∞. This is the Bromwich integral; σ can be anywhere inside the ROC.",
        "Geometrically: walk up the vertical line Re{s} = σ inside the ROC, reading off X(s) along the way (the yellow curve on the landscape).",
        "Each point s on the line contributes X(s) e^(st): a spiral weighted by X(s).",
        "Numerically, as a Riemann sum: add waves at ω = kΔω. With σ = 0.3 every one of them grows like e^(0.3t)...",
        "...yet together they rebuild the decaying e^(-t) u(t): the growing parts cancel.",
        "With all frequencies (the integral) we get exactly x(t), including the value 0.5 at the jump (the midpoint).",
        "With the line to the right of the pole (σ = 0.3) the result is e^(-t) u(t).",
        "Slide the same line to the left of the pole (σ = -1.5): the very same X(s) now gives -e^(-t) u(-t). The line has to lie in the ROC, and a different ROC gives a different signal.",
        "In practice the line is closed with a large semicircle. For t > 0 close to the left: the contour encloses the pole, and its residue gives e^(-t).",
        "For t < 0 close to the right: nothing is inside, so x(t) = 0. That is why the result is right-sided.",
        "The Cauchy residue theorem evaluates the integral (beyond this course; the slides link a video). For rational X(s) we use partial fractions instead.",
    ],
    "PartialFractions": [
        "For a rational X(s), split it into simple terms: 1/((s + 1)(s + 2)) = A/(s + 1) + B/(s + 2).",
        "Cover-up method: A = (s + 1) X(s) at s = -1, which is 1; B = (s + 2) X(s) at s = -2, which is -1.",
        "So X(s) = 1/(s + 1) - 1/(s + 2), whatever the ROC.",
        "Each term A/(s + a) has two possible inverses: if the ROC is to the right of its pole, A e^(-at) u(t); if to the left, -A e^(-at) u(-t).",
        "Example 9.9, ROC Re{s} > -1: right of both poles, so both terms are causal: x(t) = (e^(-t) - e^(-2t)) u(t).",
        "Example 9.10, ROC Re{s} < -2: left of both poles, so both terms are anticausal: x(t) = (-e^(-t) + e^(-2t)) u(-t).",
        "Example 9.11, -2 < Re{s} < -1: the ROC is right of -2 (causal term) but left of -1 (anticausal term): x(t) = -e^(-t) u(-t) - e^(-2t) u(t).",
        "Recipe: expand in partial fractions, check which side of each pole the ROC is on, invert each term, add them up.",
    ],
}
